### PR TITLE
Static artifact direct

### LINKED ISSUE #7: Add bioconda recipe for sequenceTools
The bionconda recipe for sequenceTools will give another way for people to install it easily. It will also make it easy to incorporate into eager2. The only way to get sequenceTools running in a bioconda recipe is by installing a pre-compiled static binary. To make this process easier, Travis CI can be used to build and publish this static binary automatically. Therefore there are the following things to do:

1. Create github account to be used by Travis CI
 - This will have write permission to your repos, hence the separate account to allow fine grained access control
2. Sign up for Travis CI:
 - https://docs.travis-ci.com/
3. Add a file to tell travis what to do:
 - https://github.com/gitter-bioinf/sequenceTools/blob/static-artifact-sc13/.travis.yml
4. Update bioconda recipe to install the new artifact:
 - https://github.com/sc13-bioinf/bioconda-recipes/tree/sequencetools

### PR DESCRIPTION
**Pull request by sequencetoolsconda**
This will use Travis CI to build sequencetools_static.x86_64-linux.tar.gz and publish it to:

https://github.com/sequencetoolsconda/sequenceTools/releases

The job to build this artifact is only triggered when a tag is pushed. From here it is down to:

https://github.com/sequencetoolsconda/bioconda-recipes/tree/master/recipes/sequencetools

which installs sequencetools for conda users.

### CODE REVIEW

**Comment by stschiff** [comment]
OK, so I'm not fluent enough with Travis CI or in fact, Docker. So I trust you on this. Why did you call it "static artifact", btw? It sounds like something to avoid, somehow...

**Comment by sequencetoolsconda** [comment]
Artifact is probably a term from the java world. I think its pretty much something produced by a build (e.g. dev, production etc). I called it static because we are trying to build a static binary. If you don't already have a Travis CI account then all that needs to be done is commit the PR. Everything else can then happen in the sequencetoolsconda repo (Which is linked to a Travis CI account)

**Comment by stschiff** [comment]
OK, just to understand the workflow here:
1) I push a commit with a new tag (into this repo)
2) Travis CI is triggered and builds `sequencetools_static.x86_64-linux.tar.gz` (within this repo)
3) It then deploys that tar-file to sequencetoolsconda (your repo)
4) sequencetoolsconda takes the file and somehow pushes it into bioconda (also your repo)

Correct? more or less?

**Comment by sequencetoolsconda** [comment]
Yes that would be the most direct solution. It does of course hinge on a Travis CI account being able to see your repo. Ideally only sequencetoolsconda needs a Travis CI account (unless you already have one). Right now I don't think the sequencetoolsconda account can. This is ok as Travis CI can be triggered in the sequencetoolsconda repo (slightly less direct). It might be possible for you to grant sequencetoolsconda read only access to the main sequencetools repo which would allow the direct solution as you described. Write access should not be needed as publishing is done to the sequencetoolsconda repo.

**Comment by sequencetoolsconda** [comment]
So regarding point 4. The bioconda recipe downloads the tar-file from the sequencetoolsconda/sequenceTools releases page and unpacks it. Right now the version is hard coded so the conda recipe would need updating to find a new release. I guess the recipe could automatically download the latest release or something but that can be done at some point.

**Pull request merged**
